#if UNITY_EDITOR
using System.Collections.Generic;
using Eitan.EasyMic.Runtime;
using UnityEngine;

namespace Eitan.EasyMic.Editor
{
    internal enum EasyMicPipelineTextKey
    {
        WindowTitle,
        ToolbarPlayback,
        ToolbarRecording,
        ToolbarFlow,
        ToolbarFlowTooltip,
        ToolbarFit,
        ToolbarFitTooltip,
        ToolbarMap,
        ToolbarMapTooltip,
        NoSnapshot,
        NoPipelineViewSelected,
        WelcomeTitle,
        WelcomeBody,
        WelcomeHint,
        ShowPlaybackView,
        ShowRecordingView,
        TogglePipelineViewTooltip,

        InspectorEyebrow,
        InspectorDockInitial,
        InspectorDockTooltip,
        InspectorDockRightTooltip,
        InspectorDockLeftTooltip,
        RuntimeOverview,
        RuntimeOverviewSubtitle,
        RuntimeOverviewSelectionHint,
        SelectedNode,
        Name,
        Type,
        Pipeline,
        State,
        Thread,
        Metrics,
        Playback,
        Recording,
        Runtime,
        Backend,
        Output,
        Capture,
        Graph,
        TimingAndQueues,
        Callback,
        PlaybackQueue,
        CaptureQueue,
        Xruns,
        Latency,
        Processing,
        PlaybackDsp,
        CaptureDsp,
        AsyncReaders,
        Threading,
        None,
        Running,
        Stopped,
        Active,
        Idle,
        NoActiveSessions,
        DefaultOutput,
        GraphCountsFormat,
        CallbackFormat,
        QueueSamplesPeakFormat,
        XrunsFormat,
        ThreadingPath,

        StatusFormat,
        RunningLower,
        StoppedLower,
        CaptureSessionSingular,
        CaptureSessionPlural,
        DiagnosticsTitle,
        DiagnosticsNodes,
        DiagnosticsEdges,
        DiagnosticsBoundary,

        PlaybackDeviceFallback,
        MiniaudioOutput,
        RenderQueue,
        WorkerToNativeBoundary,
        PlaybackTransport,
        PreRenderWorker,
        MasterMixer,
        PlaybackPipeline,
        ActiveOutputGraph,
        OutputGraphIdle,
        MixerSubtitleFormat,
        SourceSingular,
        SourcePlural,
        ChildMixerSingular,
        ChildMixerPlural,
        PlaybackSource,
        SourceQueue,
        StreamBuffer,
        CaptureIdle,
        WaitingForRecording,
        StartRecordingToInspect,
        RecordingPipelines,
        NoActiveCaptureSessions,
        CaptureDevice,
        CaptureDeviceFallback,
        CaptureQueueNode,
        NativeToManagedBoundary,
        CaptureTransport,
        ManagedDrainWorker,
        CaptureConsumers,
        CaptureConsumersSubtitle,
        ProcessorCountFormat,
        ProcessorSingular,
        ProcessorPlural,
        ActiveCaptureSessionsFormat,
        AsyncReader,
        DspStage,
        ProcessorStateFormat,
        EnabledLower,
        BypassedLower,

        DeviceMetricsFormat,
        RecordingMetricsFormat,
        TelemetryMetricsFormat,
        QueueMetricsFormat,
        MixerMetricsFormat,
        SourceMetricsFormat,
        MutedLower,
        SoloLower,
        ActiveLower,
        PlayingLower,
        PausedLower,

        NodeKindPlaybackDevice,
        NodeKindCaptureDevice,
        NodeKindPlaybackSource,
        NodeKindQueue,
        NodeKindTransport,
        NodeKindMixer,
        NodeKindProcessor,
        NodeKindReader,
        NodeKindWriter,
        NodeKindOutput,
        NodeKindGroup,

        ThreadNative,
        ThreadAudio,
        ThreadWorker,
        ThreadMain,
        ThreadTelemetry,
        ThreadUnknown
    }

    internal static partial class EasyMicEditorLocalization
    {
        private static readonly IReadOnlyDictionary<EasyMicPipelineTextKey, string> PipelineEnglish =
            new Dictionary<EasyMicPipelineTextKey, string>
            {
                { EasyMicPipelineTextKey.WindowTitle, "EasyMic Pipeline" },
                { EasyMicPipelineTextKey.ToolbarPlayback, "Playback" },
                { EasyMicPipelineTextKey.ToolbarRecording, "Recording" },
                { EasyMicPipelineTextKey.ToolbarFlow, "Flow" },
                { EasyMicPipelineTextKey.ToolbarFlowTooltip, "Toggle animated edge flow direction" },
                { EasyMicPipelineTextKey.ToolbarFit, "Fit" },
                { EasyMicPipelineTextKey.ToolbarFitTooltip, "Fit all visible pipeline canvases" },
                { EasyMicPipelineTextKey.ToolbarMap, "Map" },
                { EasyMicPipelineTextKey.ToolbarMapTooltip, "Show or hide the minimaps" },
                { EasyMicPipelineTextKey.NoSnapshot, "No snapshot" },
                { EasyMicPipelineTextKey.NoPipelineViewSelected, "No pipeline view selected" },
                { EasyMicPipelineTextKey.WelcomeTitle, "No Pipeline View Selected" },
                { EasyMicPipelineTextKey.WelcomeBody, "Select one or more runtime pipeline views to inspect EasyMic audio flow, device state, queues, DSP stages, and telemetry." },
                { EasyMicPipelineTextKey.WelcomeHint, "Playback focuses on output routing and source mixing. Recording focuses on capture, preprocessing, and consumer flow." },
                { EasyMicPipelineTextKey.ShowPlaybackView, "Show Playback View" },
                { EasyMicPipelineTextKey.ShowRecordingView, "Show Recording View" },
                { EasyMicPipelineTextKey.TogglePipelineViewTooltip, "Toggle {0} pipeline view" },

                { EasyMicPipelineTextKey.InspectorEyebrow, "Inspector" },
                { EasyMicPipelineTextKey.InspectorDockInitial, "Dock" },
                { EasyMicPipelineTextKey.InspectorDockTooltip, "Dock inspector left or right" },
                { EasyMicPipelineTextKey.InspectorDockRightTooltip, "Dock inspector to the right" },
                { EasyMicPipelineTextKey.InspectorDockLeftTooltip, "Dock inspector to the left" },
                { EasyMicPipelineTextKey.RuntimeOverview, "Runtime Overview" },
                { EasyMicPipelineTextKey.RuntimeOverviewSubtitle, "Readonly runtime graph inspector" },
                { EasyMicPipelineTextKey.RuntimeOverviewSelectionHint, "Select a node to inspect thread ownership, metrics, and pipeline role." },
                { EasyMicPipelineTextKey.SelectedNode, "Selected Node" },
                { EasyMicPipelineTextKey.Name, "Name" },
                { EasyMicPipelineTextKey.Type, "Type" },
                { EasyMicPipelineTextKey.Pipeline, "Pipeline" },
                { EasyMicPipelineTextKey.State, "State" },
                { EasyMicPipelineTextKey.Thread, "Thread" },
                { EasyMicPipelineTextKey.Metrics, "Metrics" },
                { EasyMicPipelineTextKey.Playback, "Playback" },
                { EasyMicPipelineTextKey.Recording, "Recording" },
                { EasyMicPipelineTextKey.Runtime, "Runtime" },
                { EasyMicPipelineTextKey.Backend, "Backend" },
                { EasyMicPipelineTextKey.Output, "Output" },
                { EasyMicPipelineTextKey.Capture, "Capture" },
                { EasyMicPipelineTextKey.Graph, "Graph" },
                { EasyMicPipelineTextKey.TimingAndQueues, "Timing & Queues" },
                { EasyMicPipelineTextKey.Callback, "Callback" },
                { EasyMicPipelineTextKey.PlaybackQueue, "Playback Queue" },
                { EasyMicPipelineTextKey.CaptureQueue, "Capture Queue" },
                { EasyMicPipelineTextKey.Xruns, "Xruns" },
                { EasyMicPipelineTextKey.Latency, "Latency" },
                { EasyMicPipelineTextKey.Processing, "Processing" },
                { EasyMicPipelineTextKey.PlaybackDsp, "Playback DSP" },
                { EasyMicPipelineTextKey.CaptureDsp, "Capture DSP" },
                { EasyMicPipelineTextKey.AsyncReaders, "Async Readers" },
                { EasyMicPipelineTextKey.Threading, "Threading" },
                { EasyMicPipelineTextKey.None, "None" },
                { EasyMicPipelineTextKey.Running, "Running" },
                { EasyMicPipelineTextKey.Stopped, "Stopped" },
                { EasyMicPipelineTextKey.Active, "Active" },
                { EasyMicPipelineTextKey.Idle, "Idle" },
                { EasyMicPipelineTextKey.NoActiveSessions, "No active sessions" },
                { EasyMicPipelineTextKey.DefaultOutput, "Default Output" },
                { EasyMicPipelineTextKey.GraphCountsFormat, "{0} nodes | {1} groups | {2} edges" },
                { EasyMicPipelineTextKey.CallbackFormat, "{0:0.00} us avg | {1:0.00} us max" },
                { EasyMicPipelineTextKey.QueueSamplesPeakFormat, "{0} samples | peak {1}" },
                { EasyMicPipelineTextKey.XrunsFormat, "PB {0}/{1} | CAP {2}/{3}" },
                { EasyMicPipelineTextKey.ThreadingPath, "native callback -> bounded queue -> managed worker" },

                { EasyMicPipelineTextKey.StatusFormat, "{0} | Playback {1} | {2} {3} | {4} nodes | {5} edges" },
                { EasyMicPipelineTextKey.RunningLower, "running" },
                { EasyMicPipelineTextKey.StoppedLower, "stopped" },
                { EasyMicPipelineTextKey.CaptureSessionSingular, "capture session" },
                { EasyMicPipelineTextKey.CaptureSessionPlural, "capture sessions" },
                { EasyMicPipelineTextKey.DiagnosticsTitle, "EasyMic Pipeline Diagnostics" },
                { EasyMicPipelineTextKey.DiagnosticsNodes, "Nodes" },
                { EasyMicPipelineTextKey.DiagnosticsEdges, "Edges" },
                { EasyMicPipelineTextKey.DiagnosticsBoundary, "boundary" },

                { EasyMicPipelineTextKey.PlaybackDeviceFallback, "Playback Device" },
                { EasyMicPipelineTextKey.MiniaudioOutput, "miniaudio output" },
                { EasyMicPipelineTextKey.RenderQueue, "Render Queue" },
                { EasyMicPipelineTextKey.WorkerToNativeBoundary, "worker to native boundary" },
                { EasyMicPipelineTextKey.PlaybackTransport, "Playback Transport" },
                { EasyMicPipelineTextKey.PreRenderWorker, "pre-render worker" },
                { EasyMicPipelineTextKey.MasterMixer, "Master Mixer" },
                { EasyMicPipelineTextKey.PlaybackPipeline, "Playback Pipeline" },
                { EasyMicPipelineTextKey.ActiveOutputGraph, "active output graph" },
                { EasyMicPipelineTextKey.OutputGraphIdle, "output graph idle" },
                { EasyMicPipelineTextKey.MixerSubtitleFormat, "{0} {1}, {2} {3}" },
                { EasyMicPipelineTextKey.SourceSingular, "source" },
                { EasyMicPipelineTextKey.SourcePlural, "sources" },
                { EasyMicPipelineTextKey.ChildMixerSingular, "child mixer" },
                { EasyMicPipelineTextKey.ChildMixerPlural, "child mixers" },
                { EasyMicPipelineTextKey.PlaybackSource, "playback source" },
                { EasyMicPipelineTextKey.SourceQueue, "Source Queue" },
                { EasyMicPipelineTextKey.StreamBuffer, "stream buffer" },
                { EasyMicPipelineTextKey.CaptureIdle, "Capture Idle" },
                { EasyMicPipelineTextKey.WaitingForRecording, "waiting for recording" },
                { EasyMicPipelineTextKey.StartRecordingToInspect, "Start a recording to inspect capture topology" },
                { EasyMicPipelineTextKey.RecordingPipelines, "Recording Pipelines" },
                { EasyMicPipelineTextKey.NoActiveCaptureSessions, "no active capture sessions" },
                { EasyMicPipelineTextKey.CaptureDevice, "capture device" },
                { EasyMicPipelineTextKey.CaptureDeviceFallback, "capture device (fallback)" },
                { EasyMicPipelineTextKey.CaptureQueueNode, "Capture Queue" },
                { EasyMicPipelineTextKey.NativeToManagedBoundary, "native to managed boundary" },
                { EasyMicPipelineTextKey.CaptureTransport, "Capture Transport" },
                { EasyMicPipelineTextKey.ManagedDrainWorker, "managed drain worker" },
                { EasyMicPipelineTextKey.CaptureConsumers, "Capture Consumers" },
                { EasyMicPipelineTextKey.CaptureConsumersSubtitle, "readers, files, integrations" },
                { EasyMicPipelineTextKey.ProcessorCountFormat, "{0} {1}" },
                { EasyMicPipelineTextKey.ProcessorSingular, "processor" },
                { EasyMicPipelineTextKey.ProcessorPlural, "processors" },
                { EasyMicPipelineTextKey.ActiveCaptureSessionsFormat, "{0} active {1}" },
                { EasyMicPipelineTextKey.AsyncReader, "async reader" },
                { EasyMicPipelineTextKey.DspStage, "DSP stage" },
                { EasyMicPipelineTextKey.ProcessorStateFormat, "#{0}  {1}" },
                { EasyMicPipelineTextKey.EnabledLower, "enabled" },
                { EasyMicPipelineTextKey.BypassedLower, "bypassed" },

                { EasyMicPipelineTextKey.DeviceMetricsFormat, "{0} Hz | {1} ch | {2}" },
                { EasyMicPipelineTextKey.RecordingMetricsFormat, "{0} Hz | {1} ch | cb {2}" },
                { EasyMicPipelineTextKey.TelemetryMetricsFormat, "avg {0:0.00} us | max {1:0.00} us\nxruns {2}/{3} | frames {4}" },
                { EasyMicPipelineTextKey.QueueMetricsFormat, "{0} samples | {1:0.0} ms\npeak {2} samples" },
                { EasyMicPipelineTextKey.MixerMetricsFormat, "vol {0:0.00} | {1}{2}\nDSP {3}" },
                { EasyMicPipelineTextKey.SourceMetricsFormat, "{0} Hz | {1} ch | {2:0.0} ms\nvol {3:0.00} | {4}" },
                { EasyMicPipelineTextKey.MutedLower, "muted " },
                { EasyMicPipelineTextKey.SoloLower, "solo" },
                { EasyMicPipelineTextKey.ActiveLower, "active" },
                { EasyMicPipelineTextKey.PlayingLower, "playing" },
                { EasyMicPipelineTextKey.PausedLower, "paused" },

                { EasyMicPipelineTextKey.NodeKindPlaybackDevice, "Playback Device" },
                { EasyMicPipelineTextKey.NodeKindCaptureDevice, "Capture Device" },
                { EasyMicPipelineTextKey.NodeKindPlaybackSource, "Playback Source" },
                { EasyMicPipelineTextKey.NodeKindQueue, "Queue" },
                { EasyMicPipelineTextKey.NodeKindTransport, "Transport" },
                { EasyMicPipelineTextKey.NodeKindMixer, "Mixer" },
                { EasyMicPipelineTextKey.NodeKindProcessor, "Processor" },
                { EasyMicPipelineTextKey.NodeKindReader, "Reader" },
                { EasyMicPipelineTextKey.NodeKindWriter, "Writer" },
                { EasyMicPipelineTextKey.NodeKindOutput, "Output" },
                { EasyMicPipelineTextKey.NodeKindGroup, "Group" },

                { EasyMicPipelineTextKey.ThreadNative, "Native realtime boundary" },
                { EasyMicPipelineTextKey.ThreadAudio, "Realtime audio callback" },
                { EasyMicPipelineTextKey.ThreadWorker, "Managed worker thread" },
                { EasyMicPipelineTextKey.ThreadMain, "Unity main thread" },
                { EasyMicPipelineTextKey.ThreadTelemetry, "Telemetry thread" },
                { EasyMicPipelineTextKey.ThreadUnknown, "Thread unknown" },
            };

        private static readonly IReadOnlyDictionary<EasyMicPipelineTextKey, string> PipelineChineseSimplified =
            new Dictionary<EasyMicPipelineTextKey, string>
            {
                { EasyMicPipelineTextKey.WindowTitle, "EasyMic 管线" },
                { EasyMicPipelineTextKey.ToolbarPlayback, "播放" },
                { EasyMicPipelineTextKey.ToolbarRecording, "录制" },
                { EasyMicPipelineTextKey.ToolbarFlow, "流向" },
                { EasyMicPipelineTextKey.ToolbarFlowTooltip, "切换边线的流向动画" },
                { EasyMicPipelineTextKey.ToolbarFit, "适配" },
                { EasyMicPipelineTextKey.ToolbarFitTooltip, "适配所有当前显示的管线画布" },
                { EasyMicPipelineTextKey.ToolbarMap, "地图" },
                { EasyMicPipelineTextKey.ToolbarMapTooltip, "显示或隐藏小地图" },
                { EasyMicPipelineTextKey.NoSnapshot, "暂无快照" },
                { EasyMicPipelineTextKey.NoPipelineViewSelected, "未选择管线视图" },
                { EasyMicPipelineTextKey.WelcomeTitle, "未选择管线视图" },
                { EasyMicPipelineTextKey.WelcomeBody, "选择一个或多个运行时管线视图，用于检查 EasyMic 的音频流、设备状态、队列、DSP 阶段和遥测。" },
                { EasyMicPipelineTextKey.WelcomeHint, "播放视图关注输出路由和音源混合。录制视图关注采集、预处理和消费者流向。" },
                { EasyMicPipelineTextKey.ShowPlaybackView, "显示播放视图" },
                { EasyMicPipelineTextKey.ShowRecordingView, "显示录制视图" },
                { EasyMicPipelineTextKey.TogglePipelineViewTooltip, "切换{0}管线视图" },

                { EasyMicPipelineTextKey.InspectorEyebrow, "检查器" },
                { EasyMicPipelineTextKey.InspectorDockInitial, "停靠" },
                { EasyMicPipelineTextKey.InspectorDockTooltip, "将检查器停靠到左侧或右侧" },
                { EasyMicPipelineTextKey.InspectorDockRightTooltip, "将检查器停靠到右侧" },
                { EasyMicPipelineTextKey.InspectorDockLeftTooltip, "将检查器停靠到左侧" },
                { EasyMicPipelineTextKey.RuntimeOverview, "运行时概览" },
                { EasyMicPipelineTextKey.RuntimeOverviewSubtitle, "只读运行时管线图检查器" },
                { EasyMicPipelineTextKey.RuntimeOverviewSelectionHint, "选择节点以检查线程归属、指标和管线角色。" },
                { EasyMicPipelineTextKey.SelectedNode, "已选节点" },
                { EasyMicPipelineTextKey.Name, "名称" },
                { EasyMicPipelineTextKey.Type, "类型" },
                { EasyMicPipelineTextKey.Pipeline, "管线" },
                { EasyMicPipelineTextKey.State, "状态" },
                { EasyMicPipelineTextKey.Thread, "线程" },
                { EasyMicPipelineTextKey.Metrics, "指标" },
                { EasyMicPipelineTextKey.Playback, "播放" },
                { EasyMicPipelineTextKey.Recording, "录制" },
                { EasyMicPipelineTextKey.Runtime, "运行时" },
                { EasyMicPipelineTextKey.Backend, "后端" },
                { EasyMicPipelineTextKey.Output, "输出" },
                { EasyMicPipelineTextKey.Capture, "采集" },
                { EasyMicPipelineTextKey.Graph, "图" },
                { EasyMicPipelineTextKey.TimingAndQueues, "时序与队列" },
                { EasyMicPipelineTextKey.Callback, "回调" },
                { EasyMicPipelineTextKey.PlaybackQueue, "播放队列" },
                { EasyMicPipelineTextKey.CaptureQueue, "采集队列" },
                { EasyMicPipelineTextKey.Xruns, "Xrun" },
                { EasyMicPipelineTextKey.Latency, "延迟" },
                { EasyMicPipelineTextKey.Processing, "处理" },
                { EasyMicPipelineTextKey.PlaybackDsp, "播放 DSP" },
                { EasyMicPipelineTextKey.CaptureDsp, "采集 DSP" },
                { EasyMicPipelineTextKey.AsyncReaders, "异步读取器" },
                { EasyMicPipelineTextKey.Threading, "线程" },
                { EasyMicPipelineTextKey.None, "无" },
                { EasyMicPipelineTextKey.Running, "运行中" },
                { EasyMicPipelineTextKey.Stopped, "已停止" },
                { EasyMicPipelineTextKey.Active, "活跃" },
                { EasyMicPipelineTextKey.Idle, "空闲" },
                { EasyMicPipelineTextKey.NoActiveSessions, "无活跃会话" },
                { EasyMicPipelineTextKey.DefaultOutput, "默认输出" },
                { EasyMicPipelineTextKey.GraphCountsFormat, "{0} 个节点 | {1} 个分组 | {2} 条边" },
                { EasyMicPipelineTextKey.CallbackFormat, "平均 {0:0.00} us | 最大 {1:0.00} us" },
                { EasyMicPipelineTextKey.QueueSamplesPeakFormat, "{0} 采样 | 峰值 {1}" },
                { EasyMicPipelineTextKey.XrunsFormat, "播放 {0}/{1} | 采集 {2}/{3}" },
                { EasyMicPipelineTextKey.ThreadingPath, "原生回调 -> 有界队列 -> 托管工作线程" },

                { EasyMicPipelineTextKey.StatusFormat, "{0} | 播放 {1} | {2} 个{3} | {4} 个节点 | {5} 条边" },
                { EasyMicPipelineTextKey.RunningLower, "运行中" },
                { EasyMicPipelineTextKey.StoppedLower, "已停止" },
                { EasyMicPipelineTextKey.CaptureSessionSingular, "采集会话" },
                { EasyMicPipelineTextKey.CaptureSessionPlural, "采集会话" },
                { EasyMicPipelineTextKey.DiagnosticsTitle, "EasyMic 管线诊断" },
                { EasyMicPipelineTextKey.DiagnosticsNodes, "节点" },
                { EasyMicPipelineTextKey.DiagnosticsEdges, "边" },
                { EasyMicPipelineTextKey.DiagnosticsBoundary, "边界" },

                { EasyMicPipelineTextKey.PlaybackDeviceFallback, "播放设备" },
                { EasyMicPipelineTextKey.MiniaudioOutput, "miniaudio 输出" },
                { EasyMicPipelineTextKey.RenderQueue, "渲染队列" },
                { EasyMicPipelineTextKey.WorkerToNativeBoundary, "工作线程到原生边界" },
                { EasyMicPipelineTextKey.PlaybackTransport, "播放传输" },
                { EasyMicPipelineTextKey.PreRenderWorker, "预渲染工作线程" },
                { EasyMicPipelineTextKey.MasterMixer, "主混音器" },
                { EasyMicPipelineTextKey.PlaybackPipeline, "播放管线" },
                { EasyMicPipelineTextKey.ActiveOutputGraph, "活跃输出图" },
                { EasyMicPipelineTextKey.OutputGraphIdle, "输出图空闲" },
                { EasyMicPipelineTextKey.MixerSubtitleFormat, "{0} 个{1}，{2} 个{3}" },
                { EasyMicPipelineTextKey.SourceSingular, "音源" },
                { EasyMicPipelineTextKey.SourcePlural, "音源" },
                { EasyMicPipelineTextKey.ChildMixerSingular, "子混音器" },
                { EasyMicPipelineTextKey.ChildMixerPlural, "子混音器" },
                { EasyMicPipelineTextKey.PlaybackSource, "播放音源" },
                { EasyMicPipelineTextKey.SourceQueue, "音源队列" },
                { EasyMicPipelineTextKey.StreamBuffer, "流式缓冲" },
                { EasyMicPipelineTextKey.CaptureIdle, "采集空闲" },
                { EasyMicPipelineTextKey.WaitingForRecording, "等待录制" },
                { EasyMicPipelineTextKey.StartRecordingToInspect, "开始录制后可检查采集拓扑" },
                { EasyMicPipelineTextKey.RecordingPipelines, "录制管线" },
                { EasyMicPipelineTextKey.NoActiveCaptureSessions, "无活跃采集会话" },
                { EasyMicPipelineTextKey.CaptureDevice, "采集设备" },
                { EasyMicPipelineTextKey.CaptureDeviceFallback, "采集设备（回退）" },
                { EasyMicPipelineTextKey.CaptureQueueNode, "采集队列" },
                { EasyMicPipelineTextKey.NativeToManagedBoundary, "原生到托管边界" },
                { EasyMicPipelineTextKey.CaptureTransport, "采集传输" },
                { EasyMicPipelineTextKey.ManagedDrainWorker, "托管排空工作线程" },
                { EasyMicPipelineTextKey.CaptureConsumers, "采集消费者" },
                { EasyMicPipelineTextKey.CaptureConsumersSubtitle, "读取器、文件、集成" },
                { EasyMicPipelineTextKey.ProcessorCountFormat, "{0} 个{1}" },
                { EasyMicPipelineTextKey.ProcessorSingular, "处理器" },
                { EasyMicPipelineTextKey.ProcessorPlural, "处理器" },
                { EasyMicPipelineTextKey.ActiveCaptureSessionsFormat, "{0} 个活跃{1}" },
                { EasyMicPipelineTextKey.AsyncReader, "异步读取器" },
                { EasyMicPipelineTextKey.DspStage, "DSP 阶段" },
                { EasyMicPipelineTextKey.ProcessorStateFormat, "#{0}  {1}" },
                { EasyMicPipelineTextKey.EnabledLower, "已启用" },
                { EasyMicPipelineTextKey.BypassedLower, "已旁路" },

                { EasyMicPipelineTextKey.DeviceMetricsFormat, "{0} Hz | {1} 声道 | {2}" },
                { EasyMicPipelineTextKey.RecordingMetricsFormat, "{0} Hz | {1} 声道 | 回调 {2}" },
                { EasyMicPipelineTextKey.TelemetryMetricsFormat, "平均 {0:0.00} us | 最大 {1:0.00} us\nxruns {2}/{3} | 帧 {4}" },
                { EasyMicPipelineTextKey.QueueMetricsFormat, "{0} 采样 | {1:0.0} ms\n峰值 {2} 采样" },
                { EasyMicPipelineTextKey.MixerMetricsFormat, "音量 {0:0.00} | {1}{2}\nDSP {3}" },
                { EasyMicPipelineTextKey.SourceMetricsFormat, "{0} Hz | {1} 声道 | {2:0.0} ms\n音量 {3:0.00} | {4}" },
                { EasyMicPipelineTextKey.MutedLower, "静音 " },
                { EasyMicPipelineTextKey.SoloLower, "独奏" },
                { EasyMicPipelineTextKey.ActiveLower, "活跃" },
                { EasyMicPipelineTextKey.PlayingLower, "播放中" },
                { EasyMicPipelineTextKey.PausedLower, "已暂停" },

                { EasyMicPipelineTextKey.NodeKindPlaybackDevice, "播放设备" },
                { EasyMicPipelineTextKey.NodeKindCaptureDevice, "采集设备" },
                { EasyMicPipelineTextKey.NodeKindPlaybackSource, "播放音源" },
                { EasyMicPipelineTextKey.NodeKindQueue, "队列" },
                { EasyMicPipelineTextKey.NodeKindTransport, "传输" },
                { EasyMicPipelineTextKey.NodeKindMixer, "混音器" },
                { EasyMicPipelineTextKey.NodeKindProcessor, "处理器" },
                { EasyMicPipelineTextKey.NodeKindReader, "读取器" },
                { EasyMicPipelineTextKey.NodeKindWriter, "写入器" },
                { EasyMicPipelineTextKey.NodeKindOutput, "输出" },
                { EasyMicPipelineTextKey.NodeKindGroup, "分组" },

                { EasyMicPipelineTextKey.ThreadNative, "原生实时边界" },
                { EasyMicPipelineTextKey.ThreadAudio, "实时音频回调" },
                { EasyMicPipelineTextKey.ThreadWorker, "托管工作线程" },
                { EasyMicPipelineTextKey.ThreadMain, "Unity 主线程" },
                { EasyMicPipelineTextKey.ThreadTelemetry, "遥测线程" },
                { EasyMicPipelineTextKey.ThreadUnknown, "未知线程" },
            };

        public static string PipelineText(EasyMicPipelineTextKey key)
        {
            var table = CurrentLanguage == EasyMicEditorLanguage.ChineseSimplified
                ? PipelineChineseSimplified
                : PipelineEnglish;
            if (table.TryGetValue(key, out string value))
            {
                return value;
            }

            return PipelineEnglish.TryGetValue(key, out string fallback) ? fallback : key.ToString();
        }

        public static string PipelineText(EasyMicPipelineTextKey key, params object[] args)
        {
            string format = PipelineText(key);
            return args == null || args.Length == 0 ? format : string.Format(format, args);
        }

        public static string PipelineViewLabel(EasyMicPipelineViewMode mode)
        {
            return mode == EasyMicPipelineViewMode.Playback
                ? PipelineText(EasyMicPipelineTextKey.Playback)
                : PipelineText(EasyMicPipelineTextKey.Recording);
        }

        public static string PipelineNodeKindLabel(EasyMicPipelineNodeKind kind)
        {
            switch (kind)
            {
                case EasyMicPipelineNodeKind.PlaybackDevice: return PipelineText(EasyMicPipelineTextKey.NodeKindPlaybackDevice);
                case EasyMicPipelineNodeKind.CaptureDevice: return PipelineText(EasyMicPipelineTextKey.NodeKindCaptureDevice);
                case EasyMicPipelineNodeKind.PlaybackSource: return PipelineText(EasyMicPipelineTextKey.NodeKindPlaybackSource);
                case EasyMicPipelineNodeKind.Queue: return PipelineText(EasyMicPipelineTextKey.NodeKindQueue);
                case EasyMicPipelineNodeKind.Transport: return PipelineText(EasyMicPipelineTextKey.NodeKindTransport);
                case EasyMicPipelineNodeKind.Mixer: return PipelineText(EasyMicPipelineTextKey.NodeKindMixer);
                case EasyMicPipelineNodeKind.Processor: return PipelineText(EasyMicPipelineTextKey.NodeKindProcessor);
                case EasyMicPipelineNodeKind.Reader: return PipelineText(EasyMicPipelineTextKey.NodeKindReader);
                case EasyMicPipelineNodeKind.Writer: return PipelineText(EasyMicPipelineTextKey.NodeKindWriter);
                case EasyMicPipelineNodeKind.Output: return PipelineText(EasyMicPipelineTextKey.NodeKindOutput);
                case EasyMicPipelineNodeKind.Group: return PipelineText(EasyMicPipelineTextKey.NodeKindGroup);
                default: return kind.ToString();
            }
        }
    }
}
#endif
